services:
  app:
    image: rilusmahmud/spl-custom-zone:main-1.0.0
    container_name: spl-custom-zone
    restart: unless-stopped
    ports:
      - "4008:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BARIKOI_API_URL=${NEXT_PUBLIC_BARIKOI_API_URL}
      - NEXT_PUBLIC_BARIKOI_API_TOKEN=${NEXT_PUBLIC_BARIKOI_API_TOKEN}
      - NEXT_PUBLIC_MAP_STYLE_URL=${NEXT_PUBLIC_MAP_STYLE_URL}
      - NEXT_PUBLIC_DEFAULT_LAT=${NEXT_PUBLIC_DEFAULT_LAT}
      - NEXT_PUBLIC_DEFAULT_LNG=${NEXT_PUBLIC_DEFAULT_LNG}
      - NEXT_PUBLIC_DEFAULT_ZOOM=${NEXT_PUBLIC_DEFAULT_ZOOM}
      - NEXT_PUBLIC_MIN_ZOOM=${NEXT_PUBLIC_MIN_ZOOM}
      - NEXT_PUBLIC_MAX_ZOOM=${NEXT_PUBLIC_MAX_ZOOM}
