# Base image - supports linux/amd64 and linux/arm64
FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set environment for standalone build
ENV NEXT_TELEMETRY_DISABLED=1

# Build arguments for environment variables
ARG NEXT_PUBLIC_BARIKOI_API_URL
ARG NEXT_PUBLIC_BARIKOI_API_TOKEN
ARG NEXT_PUBLIC_MAP_STYLE_URL
ARG NEXT_PUBLIC_DEFAULT_LAT
ARG NEXT_PUBLIC_DEFAULT_LNG
ARG NEXT_PUBLIC_DEFAULT_ZOOM
ARG NEXT_PUBLIC_MIN_ZOOM
ARG NEXT_PUBLIC_MAX_ZOOM
ARG NEXT_PUBLIC_BASEPATH

# Set build-time environment variables
ENV NEXT_PUBLIC_BARIKOI_API_URL=${NEXT_PUBLIC_BARIKOI_API_URL}
ENV NEXT_PUBLIC_BARIKOI_API_TOKEN=${NEXT_PUBLIC_BARIKOI_API_TOKEN}
ENV NEXT_PUBLIC_MAP_STYLE_URL=${NEXT_PUBLIC_MAP_STYLE_URL}
ENV NEXT_PUBLIC_DEFAULT_LAT=${NEXT_PUBLIC_DEFAULT_LAT}
ENV NEXT_PUBLIC_DEFAULT_LNG=${NEXT_PUBLIC_DEFAULT_LNG}
ENV NEXT_PUBLIC_DEFAULT_ZOOM=${NEXT_PUBLIC_DEFAULT_ZOOM}
ENV NEXT_PUBLIC_MIN_ZOOM=${NEXT_PUBLIC_MIN_ZOOM}
ENV NEXT_PUBLIC_MAX_ZOOM=${NEXT_PUBLIC_MAX_ZOOM}
ENV NEXT_PUBLIC_BASEPATH=${NEXT_PUBLIC_BASEPATH}

# Debug: Verify env vars are set
RUN echo "NEXT_PUBLIC_MAP_STYLE_URL=$NEXT_PUBLIC_MAP_STYLE_URL" && \
    echo "NEXT_PUBLIC_BARIKOI_API_URL=$NEXT_PUBLIC_BARIKOI_API_URL" && \
    test -n "$NEXT_PUBLIC_MAP_STYLE_URL" || (echo "ERROR: NEXT_PUBLIC_MAP_STYLE_URL is empty" && exit 1)

# Build Next.js application with standalone output
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Runtime environment variables (can be overridden at runtime)
ARG NEXT_PUBLIC_BARIKOI_API_URL
ARG NEXT_PUBLIC_BARIKOI_API_TOKEN
ARG NEXT_PUBLIC_MAP_STYLE_URL
ARG NEXT_PUBLIC_DEFAULT_LAT
ARG NEXT_PUBLIC_DEFAULT_LNG
ARG NEXT_PUBLIC_DEFAULT_ZOOM
ARG NEXT_PUBLIC_MIN_ZOOM
ARG NEXT_PUBLIC_MAX_ZOOM
ARG NEXT_PUBLIC_BASEPATH

ENV NEXT_PUBLIC_BARIKOI_API_URL=${NEXT_PUBLIC_BARIKOI_API_URL}
ENV NEXT_PUBLIC_BARIKOI_API_TOKEN=${NEXT_PUBLIC_BARIKOI_API_TOKEN}
ENV NEXT_PUBLIC_MAP_STYLE_URL=${NEXT_PUBLIC_MAP_STYLE_URL}
ENV NEXT_PUBLIC_DEFAULT_LAT=${NEXT_PUBLIC_DEFAULT_LAT}
ENV NEXT_PUBLIC_DEFAULT_LNG=${NEXT_PUBLIC_DEFAULT_LNG}
ENV NEXT_PUBLIC_DEFAULT_ZOOM=${NEXT_PUBLIC_DEFAULT_ZOOM}
ENV NEXT_PUBLIC_MIN_ZOOM=${NEXT_PUBLIC_MIN_ZOOM}
ENV NEXT_PUBLIC_MAX_ZOOM=${NEXT_PUBLIC_MAX_ZOOM}
ENV NEXT_PUBLIC_BASEPATH=${NEXT_PUBLIC_BASEPATH}

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy built application from builder
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
